services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://0.0.0.0:8000/v1/students
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://0.0.0.0:8000/v1/students
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
