version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://0.0.0.0:8000/v1/students}
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://0.0.0.0:8000/v1/students}
    restart: unless-stopped
